
#ifndef CONFIG_H_
#define CONFIG_H_

#define ADC_PIN 255
#define ADC0_RESOLUTION ADC_RESOLUTION_8BIT

#define BREAKPOINT asm("nop")

#define TWI_SDA_PINMUX 0xFF //PINMUX_PA16C_SERCOM1_PAD0
#define TWI_SCL_PINMUX 0xff	//PINMUX_PA17C_SERCOM1_PAD1
#define TWI_MODULE SERCOM3
#define I2C_TIMEOUT 10000
#define TWI_SDA_PIN PIN_PA23C_SERCOM3_PAD1
#define TWI_SCL_PIN PIN_PA22C_SERCOM3_PAD0
#define TWI_SDA_PINMUX PINMUX_PA23C_SERCOM3_PAD1
#define TWI_SCL_PINMUX PINMUX_PA22C_SERCOM3_PAD0

#define TWI_BUFFER_SIZE 64

#define USB_TX_PINMUX PINMUX_PA16C_SERCOM1_PAD0
#define USB_RX_PINMUX PINMUX_PA17C_SERCOM1_PAD1
#define USB_MUX USART_RX_1_TX_0_XCK_1
#define USB_MODULE SERCOM4

#define DMX_MUX USART_RX_1_TX_0_XCK_1
#define DMX_MODULE SERCOM5
#define DMX_UNIVERSE_SIZE 512
#define DMX_TX_PINMUX PINMUX_PB16C_SERCOM5_PAD0
#define DMX_RX_PINMUX PINMUX_PB17C_SERCOM5_PAD1

#endif